name: Automated API tests using Postman CLI
'on': push
jobs:
  automated-api-tests:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: 'postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}'
      - name: npm Install Newman-Reporter-Htmlextra
        run: npm install -g newman-reporter-htmlextra
      - name: Run API tests
        run: >-
      - name: Step 3 Execute collection
        run: newman run ./collection.json -e ./env.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/Report.htm       
      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
            name: report
            path: ./results/Report.html
