name: Automated API tests using Postman CLI
'on': push
jobs:
  automated-api-tests:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: 'postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}'
      - name: npm Install Newman-Reporter-Htmlextra
        run: npm install -g newman-reporter-htmlextra
      - name: Run API tests
        run: >-
          postman collection run "14374889-f9b0d308-591d-4dcf-8d76-8b05d8a90f86"
          -e "14374889-a79a801d-8a33-470b-bbcb-4b0858912fee" public/Report.html
      - name: production artifacts
        uses: actions/upload-artifact@v2
        with:
            name: report
            path: public/Report.html
